import React from 'react'

export default function PBPrivacyPolicy() {
    return (
        <>
            <section className="flex flex-col bg-white gap-3 px-5 pb-10">
                <div className="container max-w-[1024px] mx-auto flex flex-col gap-3">

                    <h5 className="text-slate-700 text-xl sm:text-2xl py-5 font-medium">Privacy Policy</h5>

                    <h5 className="text-slate-700 text-md sm:text-lg font-medium">1. Definition</h5>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">1.1 For the purpose of this organization privacy policy, the Company shall mean Anya girlchild Foundation, its subsidiaries and affiliated companies; the Customer shall mean recipient of the Services provided by the Company; the Services shall mean any physical, management and information services provided to the Customer; Goods shall mean cargo and any container not supplied by or on behalf of the Company, in which the Company provides Services.</p>



                    <h5 className="text-slate-700 text-md sm:text-lg font-medium">2. Tariff and Billing</h5>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">2.1 In consideration of the Services provided by the Company, the Customer shall pay to the Company charges based on the Company’s standard tariff unless otherwise agreed upon. The standard tariff is subject to change without notice.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">2.2 The Company shall invoice the Customer for the Service Charges for Services provided and the Customer shall inform the Company of any dispute or discrepancy found in the invoice within 7 days. Customer shall pay to the Company the invoice on time.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">2.3 The Customer shall pay for the invoice when due without deduction or deferment on account of any claim, counterclaim or set-off. The Company is entitled to impose interest on the overdue sum of money without prejudice to other rights or remedies it may have.</p>



                    <h5 className="text-slate-700 text-md sm:text-lg font-medium">3. Instructions From the Customer</h5>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">3.1 The Customer shall give sufficient timely and executable Instructions, and provide assistance and co-operation as may be necessary in the performance of the Services by the Company. “Instructions” means those instructions given by the Customer or any person authorized by the Customer in connection with the Services and Goods.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">3.2 The Customer warrants at all times that the description, particulars and the Instructions for the Services and the Goods are complete and accurate.</p>

                    <h5 className="text-slate-700 text-md sm:text-lg font-medium">3.3</h5>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">3.3.1 The Customer must explicitly inform the Company about the nature of the Goods, including but not limited to Dangerous Goods, in their instruction to the Company. “Dangerous Goods” includes goods that are or may become dangerous, inflammable, radio-active, likely to damage nature or environment; liable to taint or affect other goods or goods likely to harbour or encourage vermin or other pests or otherwise under local laws rules and regulations as identified as dangerous.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">3.3.2 If the Customer is in breach of clause 3.3.1, Customer agrees to be responsible and liable for all loss or damage whatsoever caused by the Goods howsoever arising and shall defend, indemnify and hold harmless the Company against all penalties, claims, damages, costs and expenses whatsoever arising in connection therewith and the Goods may without notice be destroyed or otherwise dealt with at the sole discretion of the Company or any other person in whose custody they may be at the relevant time.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">3.3.3 If the Company agrees to provide Services for Dangerous Goods, Customer agrees that such Services are provided subject to Customer agreement that if in the reasonable opinion of the Company or any other person, the Dangerous Goods shall at any times present a risk to other goods, property, life or health, the Company may without notice or liability destroy or otherwise deal with the Goods at the expense of the Customer.</p>

                    <h5 className="text-slate-700 text-md sm:text-lg font-medium">4. Liability of the Company</h5>
                    <h5 className="text-slate-700 text-md sm:text-lg font-medium pt-2">4.1</h5>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">4.1.1 The Company shall be liable for the loss or damage to the Goods occurring while in the sole custody or control of the Company until the time when the Goods ceased to be in the sole custody or control of the Company. the Company shall not be liable for in transit damage whether it is concealed or not visible at the time of loading or unloading or damaged while the Goods are not in its sole custody or control.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">4.1.2 In all circumstances, the Company shall have no liability whatsoever for the misdelivery of Goods in its actual or constructive possession to persons holding forged or fraudulent documents which reasonably purport to be original Bills of Lading or other original documents entitling them to possession, so long as the Company or any person authorized by him acts innocently and does not intentionally deliver the Goods to persons known by him or them to have no right to possession under the Bill of Lading.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">4.2 Any provision herein to the contrary notwithstanding, the Company shall not be liable for any loss or damage whatsoever arising from any of the following:</p>

                    <div className="p-3 flex flex-col">
                        <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">(a) the act, omission, neglect or default of the Customer or Owner or any person acting on their behalf;</p>
                        <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">(b) compliance with the Instructions given to the Company by the Customer or any other person entitled to give the same by the Customer, including appointment or use of Customer’s designated third party vendors or service providers (including but not limited to truckers, feeders, rail, carriers, warehouse or depot);</p>
                        <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">(c) illegal, false, inaccurate or insufficient description of Goods or other particulars provided by Customer, Owner or any person acting on their behalf for the Goods;</p>
                        <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">(d) insufficient packing or labelling of the Goods, or defective condition of packing except where such packing was provided by the Company;</p>
                        <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">(e) handing, loading, stowage or unloading of the Goods by the Customer, its designated third party vendors or service providers so specified by Customer, Owner or any person acting on their behalf;</p>
                        <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">(f) inherent vice and/or ordinary wear and tear and/or latent defect of the Goods;</p>
                        <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">(g) insufficient or inadequate marks on the covering of the Goods;</p>
                        <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">(h) loss or damage of the Goods whilst the Company is not in actual custody or control of the Goods;</p>
                        <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">(i) an Event of Force Majeure as defined in clause 9 herein or any other event which the Company cannot prevent its occurrence which causes the damage;</p>
                        <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">(j) Emergency measures taken by the Company in times of urgency</p>
                        <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">(k) any act, neglect or default not caused solely by the Company.</p>
                        <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify py-5 text-xs sm:text-sm">“Owner” includes the owner, shipper and consignee of the Goods and any other person who is interested or may have an interest in the Goods and any person acting on their behalf.</p>
                    </div>

                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">4.3 For the avoidance of doubt, the Company shall not in any event be held liable for any acts or omissions by the Customer’s designated third party vendors or service providers.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">4.4 The Company shall not in any event be liable for economic loss in any form, such as indirect or consequential loss or damage, loss of profits or earnings, punitive or special damages however caused, or for any loss to purchasers and other third parties to the other.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">4.5 If any of the Goods is found damaged during storage or in transit, the Company shall contact the Customer immediately advising the nature, cause and extent of damage. The Customer shall advise the Company of the appropriate actions to be taken. Goods damaged which the Company may have liability, shall be jointly surveyed by the Company and the Customer and liability (if any) is only accepted by the Company after the joint survey. Any claims made by the Customer must be subject to joint survey and presented in writing to the Company within 14 days after the Customer is notified of the occurrence of damage or loss. the Company shall immediately inform the Customer of any discrepancy found between the Goods and the documentation received.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">4.6 Advice, information or Services provided by the Company gratuitously is provided on the basis that the Company did not accept any liability whatsoever, whether in tort or bailment or otherwise.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">4.7 Under emergency situation, the Company will act in good faith and use its discretion to protect the Customer interest by taking appropriate actions to salvage the value of the Goods. The Customer will hold the Company free from claims of any kind.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">4.8 For the provision of Services and to the extent that the Company is liable, the Customer agrees that the maximum liability of the Company with respect to the losses and damages of the Goods in its provision of Services shall not exceed USD50,000 per incident.</p>

                    <h5 className="text-slate-700 text-md sm:text-lg font-medium">5. Indemnification</h5>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">5.1 The Company and the Customer shall upon demand defend, hold harmless and indemnify each other from and against all claims, lawsuits, demands, liability, costs, fines, penalties, loss, damages and expenses caused by, arising out of, or connected with any injury to or death of persons, or damage to property, arising out of the intentional acts or out of the negligent performance of the Services, including attorney’s fees and other reasonable costs of defence. To the extent any loss in question arises from the joint negligence of the Customer and the Company, liability as between the Parties shall be determined on the basis of comparative negligence.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">5.2 The Customer and/or Owner (as the case may be) shall defend, indemnify and hold harmless the Company against all claims, lawsuits, demands, liability, costs, fines, penalties, loss, damages and expenses howsoever caused by, arising out of or connected with (i) the nature of the Goods save to the extent that caused by the Company’s negligence, (ii) the Company acting in accordance with Instructions, (iii) any injury to or death of persons, or loss or damage to property, damage to the environment incurred or suffered by the Company or a third party, and resulting in any way from the performance of Services; or (iv) a breach of warranty or obligation by the Customer or the negligence of the Customer and/or Owner (as the case may be).</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">5.3 Except to the extent caused by the Company’s negligence, the Customer and/or Owner (as the case may be) shall be liable for and shall defend, indemnify and hold harmless the Company in respect of all duties, taxes, imposts, levies, deposits and outlays of whatsoever nature levied by any Authority and for all payments, fines, costs, expenses, loss and damage whatsoever incurred or sustained by the Company in connection therewith. “Authority” means a duly constituted legal or administrative person, acting within its legal powers and exercising jurisdiction within any nation, state, municipality, port or airport.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">5.4 Advice and information, in whatever form, are provided by the Company for the Customer only and the Customer shall not pass such advice or information to any third party without the Company’s written agreement. The Customer shall defend, indemnify and hold harmless the Company for all claims, lawsuits, demands, liability, loss, damage, costs and expenses howsoever caused by, arising out of or in connection with any other person relying on such advice or information.</p>

                    <h5 className="text-slate-700 text-md sm:text-lg font-medium">6. Risk and Title of Goods</h5>

                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">6.1 All Goods received and accepted by the Company to provide Services to Customers shall remain the property and risks of the Customer. The risks, title and liabilities on the Goods shall not in any way be with the Company.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">6.2 The Company shall make no representations prejudicial to Customer’s title and ownership rights to the Goods.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">6.3 the Company shall have a particular and general lien on all Goods and/or documents relating to Goods in its possession for all sums of whatsoever kind and nature due at any time from the Customer and/or Owner (as the case may be) and on giving 30 days' notice (unless otherwise decided due to the nature of the Goods such as perishables, and time sensitive merchandise) in writing to the Customer, shall be entitled to sell or dispose of such Goods and/or documents, execute any documents and/or do anything arising from or in connection with the sale or disposition of the Goods in its absolute discretion at the expense of the Customer and without any liability to the Customer and Owner and apply the proceeds in or towards the payment of such sums. Upon accounting to the Customer for any balance remaining after payment of any sum due to the Company and the costs of sale or disposal the Company shall be discharged of any liability whatsoever in respect of the Goods and/or documents. If on the sale of the Goods the proceeds fail to realise the amount due, the Company shall be entitled to recover the difference from any of the parties, Customer and/or Owner (as the case may be).</p>


                    <h5 className="text-slate-700 text-md sm:text-lg font-medium">7. Insurance</h5>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">7.1 Customer agrees that the Company is under no obligation to take out nor maintain any insurance policy in relation to the Goods. Customer shall at its own cost provide all-risk insurance including but not limited to fire, marine, theft or perils to cover the Goods while in transit and in storage.</p>

                    <h5 className="text-slate-700 text-md sm:text-lg font-medium">8. No Assignment</h5>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">8.1 Unless otherwise provided, neither the Company nor the Customer shall be permitted to assign or transfer, in whole or in part, any right, duty, responsibility or obligation contained herein without the written consent of the other party. Customer agrees that the Company may transfer or assign all or any of its rights and obligations to any of its direct or indirect holding companies or subsidiaries, affiliates as defined in clause 1.</p>

                    <h5 className="text-slate-700 text-md sm:text-lg font-medium">9. Force Majeure</h5>

                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">9.1 In the Event of Force Majeure, both the Company and the Customer shall be excused from performing or delay in performing the Services and obligations contained herein.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">9.2 Each Party agrees to give the other Party immediate oral notice of an Event of Force Majeure, stating its course and probable duration, followed by a written notice as soon as practical. Such Party shall notify the other Party immediately upon termination of such cause.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">9.3 “Event of Force Majeure” as defined herein means fire, flood, explosion, typhoon, earthquake, sandstorm, windstorm, infection disease, epidemic, pandemic, riots, calamities, strikes, lockout, labour shortage or dispute, war, other acts of God, acts or requests of government, accident, change of regulations or rules or law or government policy which renders a Party incapable of performing any of its obligations hereunder or resulting in an inability to obtain material, power, equipment or transportation from the occurrence of such circumstances, computer virus, the failure of the other Party, or any other unforeseen cause beyond the control of such Party.</p>

                    <h5 className="text-slate-700 text-md sm:text-lg font-medium">10. Independent Contractor</h5>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">10.1 Unless otherwise provided, save to the extent that the performance of Services are provided by the Company, its employees, affiliates, agents or subcontractors nominated, instructed or appointed by the Company in its entire sole discretion, the Company shall be an independent contractor and not an agent or employee of the Customer. The Company shall have exclusive control and management of its employees, affiliates, agents or subcontractors in the provision of the Services, and shall assume full responsibility for the acts and omissions of such persons only. The Company shall be entitled to subcontract all or any part of its obligations without obtaining consent from the Customer provided that the Company shall remain for the obligations under this Contract.</p>

                    <h5 className="text-slate-700 text-md sm:text-lg font-medium">11. Notice</h5>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">11.1 All notices shall be in writing and shall be properly given and delivered at the address of the recipient last known to the other.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">11.2 Any such notice may be delivered by hand, courier or registered letter and shall be deemed to have been received:</p>

                    <div className="p-5">
                        <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">(a) by hand delivery- at the time of delivery;</p>
                        <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">(b) by courier- 24 hours after the date of delivery to courier; and</p>
                        <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">(c) by registered mail- 5 working days after the date of mailing.</p>
                    </div>


                    <h5 className="text-slate-700 text-md sm:text-lg font-medium">12. Compliance with Laws and Regulations</h5>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">12.1 The Company and the Customer shall observe and comply with all applicable local and national laws, rules, regulations, orders and decrees as may be enacted or amended from time to time.</p>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">12.2 If any legislation is compulsorily applicable to any business undertaken, this Terms and Conditions shall be read as subject to such legislation and nothing herein shall be construed as a surrender by the Company of any of its rights or immunities or as an increase of any of its responsibilities or liabilities under such legislation.</p>

                    <h5 className="text-slate-700 text-md sm:text-lg font-medium">13. Confidentiality</h5>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">13.1 The Company and the Customer agree to keep confidential each other’s trade secrets, information, data and documents obtained or received under or by reason of Services provided herein, including but not limited to the procedures, business operations. Neither Party shall make any disclosure of the Confidential Information without written consent of the other Party unless and to the extent that such disclosure is required by law or regulatory requirements.</p>

                    <h5 className="text-slate-700 text-md sm:text-lg font-medium">14. Governing Law</h5>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">14.1 This Business Terms and Conditions shall be governed and construed by the English law.</p>

                    <h5 className="text-slate-700 text-md sm:text-lg font-medium">Personal Data Protection</h5>
                    <p style={{ lineHeight: 1.5 }} className="text-slate-500 leading-loose text-justify text-xs sm:text-sm">15.1 The parties agree to fully comply with General Data Protection Regulation 2016/679 (“GDPR”) and any applicable data protection laws and be bound by the terms available at https://www.oocllogistics.com/resources/PDP_FWK_E.pdf (“Framework”) under which the Customer is the “data controller” and the Company is the “data processor” in respect of any personal data provided by the Customer to the Company  for the contract of carriage/ logistics/ supply chain management services.  The Customer  (i) authorises the Company to process any personal data provided to the Company or which is made available to the Company by the Customer  for the purposes of providing service under this contract and for other purposes including transferring personal data to competent bodies, courts or regulatory authorities, as may be requested; (ii) acknowledges and agrees that the Company may transfer the personal data to its affiliates, employees, agents, delegates, sub-processors or competent authorities and to a country outside of the European Economic Area and the United Kingdom in accordance with such latest applicable Standard Contractual Clauses as set out in the Framework and/or other available data transfer solutions.</p>
                </div>
            </section>
        </>
    )
}
